### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by SimoneGarbin** [ederfmartins/rgb_keyboard#3]
Hi, I installed the driver but when I try to use it I get this error:

keyboard/driver.py", line 23, in KeyboardControler TypeError: 'type' object is not subscriptable

**Comment by ederfmartins** [comment]
Hi @SimoneGarbin, thanks for pointing out this error and sorry for the late replay. Now it is fixed. If you please you could try it again, it will work this time.
